class Strings {
  Strings._();
  static const somethingWentWrong = 'Something Went Wrong';
  static const boldConnectCopyrights = '$appName © 2024 v1.0';
  static const appName = 'Bold Connect';
  static const signIn = 'Sign In';
  static const signOut = 'Sign Out';
  static const logOut = 'Log Out';
  static const signUp = 'Sign Up';
  static const checkIn = 'Check In';
  static const checkOut = 'Check Out';
  static const settings = 'Settings';
  static const confirmCode = 'Confirm Code';
  static const resetPassword = 'Reset Password';
  static const editPassword = 'Edit Password';
  static const changePasword = 'Change Password';
  static const oldPassword = 'Old Password';
  static const newPassword = 'New Password';
  static const confirmPassword = 'Confirm Password';
  static const myAccount = 'My Account';
  static const contactUs = 'Contact Us';
  static const shareLogFile = 'Share Log File';
  static const notLogsFound = 'No logs found.';
  static const appLogsForAppDebug = 'Application logs for debugging $appName';
  static const resendCode = 'Resend Code';
  static const searchAJob = 'Search a Job';
  static const signedUpConfirmation = 'Signed Up now Confirm the code';
  static const newConfirmCodeSent = 'New Confirmation code sent to your email';
  static const emailHint = 'Ex: Mark_Johnny@gmail.com';
  static const passwordHint = 'Password';
  static const email = 'Email';
  static const phoneNumber = 'Phone Number';
  static const emergencyNumber = 'Emergency Number';
  static const haveDrivingLicense = 'Have Driving License?';
  static const organization = 'Organization';
  static const general = 'General';
  static const enterEmail = 'Enter your email';
  static const enterPassword = 'Enter your password';
  static const enterConfirmCode = 'Enter Confirmation code';
  static const enterConfirmPassword = 'Enter Confirm Password';
  static const passwordsNotMatch = 'Passwords do not match';
  static const newPasswordCannotBeOldPassword =
      'New Password cannot be the same as Old Password';
  static const passwordChanged = 'Password has changed successfully.';
  static const discoverNow = 'DISCOVER NOW';
  static const findYourOnDemandWorker = 'Find Your On- Demand\nService Worker';
  static const noOfCustomerReviews = '2247+';
  static const customerReviews = 'Customer Reviews';
  static const noOfExperts = '10+';
  static const update = 'Update';
  static const save = 'Save';
  static const expertWorkers = 'Expert Workers';
  static const noOfServices = '1500+';
  static const services = 'Services Categories';
  static const hi = 'Hi,';
  static const goodToSeeYou = 'It’s Good to See you Again';
  static const signInWithReq = 'Sign In with required details';
  static const signInToAccount = 'Sign In to account';
  static const createAccount = 'Create Account';
  static const signInWithFingerPrint = 'Sign In to Account With Finger Print';
  static const enterValidEmail = 'Enter a valid email';
  static const minCharLength = 'Password must be at least 8 characters';
  static const min1Digit = 'Password must contain at least 1 digit';
  static const welcome = 'Welcome';
  static const exampleMail = 'omaraalvi.giki@gmail.com';
  static const min1SpecialChar =
      'Password must contain at least 1 special character';
  static const min1UpperCase =
      'Password must contain at least 1 uppercase letter';
  static const min1LowerCase =
      'Password must contain at least 1 lowercase letter';
  static const enterValidConfirmCode =
      'Enter a valid six-digit confirmation code';
  static const checkInCheckOut = 'Check In / Check Out';
  static const location = 'Location';
  static const showDetails = 'Show Details';
  static const noImageSelected = 'No image selected. $somethingWentWrong';
  static const noImage = 'No Image is Clicked. $somethingWentWrong';
  static const imageUploaded = 'Image uploaded successfully';
  static const cropImage = 'Crop Image';
  static const imageNotCropped = 'Image not Cropped. $somethingWentWrong';
  static const faceDetected = 'Face Detected';
  static const noFaceDetected = 'No Face Detected. $somethingWentWrong';
  static const imageNotUploaded = 'Image not Uploaded. $somethingWentWrong';
  static const locationDetected = 'Location Detected';
  static const enableLocationAllTime =
      'Enable Location Services: Allow all the time';
  static const checkInUpdateSuccess = 'You are Checked In';
  static const youAreCheckedOut = 'You Have Been Checked Out';
  static const noRecordExist = 'No Security officer record exists!';
  static const noShiftExist = 'No shift exists!';
  static const enableLocationServices = 'Enable Location Services';
  static const checkedInAlready = 'You are already Checked In.';
  static const checkedOutSuccess = "The officer has checked out now!!";
  static const checkedOutFailed = "The officer has not checked out yet!!";
  static const checkedInHistory = 'Checked In History';
  static const noHistory = 'No History Found';
  static const noUpcomingShifts = 'No Upcoming Shifts Found';
  static const noShiftsRequiringApproval = 'No Shifts Requiring Approval';
  static const noShiftsAvailable = 'No Shifts Available';
  static const historyDetails = 'History Details';
  static const preciseOn = 'Precise: On';
  static const completedShifts = 'COMPLTED SHIFT';
  static const upcomingShifts = 'UPCOMING SHIFTS';
  static const shiftsRequiringYourApproval = "Shifts Requiring Your Approval";
  static const openAndOpenNApprovalShifts = 'Open & Open With Approval Shifts';
  static const applyForShifts = "Apply for Shifts";
  static const shiftsPendingAdminApproval = "Shifts Pending Admin Approval";
  static const jobLocation = 'JOB LOCATION';
  static const jobDescription = 'JOB DESCRIPTION';
  static const shiftDetails = 'Shift Details';
  static const startDateTime = 'START DATE / TIME';
  static const endDateTime = 'END DATE / TIME';
  static const shiftDuration = 'Shift Duration';
  static const shiftsAvailable = 'Shifts Available';
  static const jobType = 'Job Type';
  static const salary = 'Salary';
  static const time = 'Time';
  static const welcomeback = 'Welcome Back!';
  static const apply = 'Apply';
  static const accept = 'Accept';
  static const reject = 'Reject';
  static const month = 'Month';
  static const completeYourProfile = 'Complete Your profile';
  static const complete = 'Complete';
  static const profile = 'Profile';
  static const incomeThisMonth = 'Income this Month';
  static const totalHoursWorked = 'Total Hours Worked';
  static const seeAll = 'See all';
  static const featuredJobs = 'Featured Jobs';
  static const upcomingShiftsLower = 'Upcoming Shifts';
  static const administration = 'Administration';
  static const fullTime = 'Full-Time';
  static const junior = 'Junior';
  static const overview = 'Overview';
  static const personalInfo = 'Personal Information';
  static const industry = 'Industry';
  static const security = 'Security';
  static const cleaning = 'Cleaning';
  static const technology = 'Technology';
  static const concierge = 'Concierge';
  static const days = "Days";
  static const miles = "Miles";
  static const searchJobs = 'Search Jobs';
  static const jobDetails = 'JOB DETAILS';
  static const siteAddress = 'Site Address';
  static const date = 'Date';
  static const price = 'Price';
  static const notifications = 'Notifications';
  static const newNotification = 'New Notification';
  static const successfullyConsented = 'Successfully consented';
  static const fullTimeSecurityOfficer =
      'Full time Security Officer in Swindon';
  static const securityOfficer = 'Security Officer';
  static const notificationChannelDescription =
      'For Showing Message Notifications';
  static const youAreUnAuthorizedToAccess = 'You Are UnAuthorized to Access';
  static const appliedSuccessfully = "Applied to shift Successfully";
  static const officerNotOnSite =
      'The officer can not checkin because he is not on security site';
  static const permissionsNotGranted =
      'Either Location or Camera or both permissions are not granted.';
  static const howManyDaysPerWeekCanYouWork =
      'How many days you can work per week?';
  static const howManyMilesAreYouWillingtoTravel =
      'How many miles you are willing to travel ?';
  static const thereAreNoNotes = "There are no notes for this shift";
  static const locationNotDetected =
      'Location not Detected. $somethingWentWrong';
  static const locationNotFound = 'Location not found. $somethingWentWrong';
  static const officerIsOnSite = "The officer is on site";
  static const pickProfilePic = 'Pick Profile Picture';
  static const locationServiceDisabled =
      "Location Service Disabled Enable Your Device's Location Service. $somethingWentWrong";
  static const cameraNotLoaded = 'Camera not loaded. $somethingWentWrong';
  static const checkYourNetworkConnection = 'Check Your Network Connection';
  static const profileImageUploaded = "Profile image has saved successfully";
  static const constJobDesc =
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour";
}
